language: generic
matrix:
  fast_finish: true

install:
  - cd ${HOME}
  - wget https://github.com/futurecore/revelation/archive/master.zip
  - unzip -qq master.zip
  - mv revelation-master revelation
  - cd ${TRAVIS_BUILD_DIR}

script:
  - ./.test_binaries.sh
